
import './Loader.css';
export const Loader = ()=>{

        return(
          
            <div className='spinner'>
            
            <i>
              <b></b> 
            </i>
            <i>
              <b></b>
            </i>
            <i>
              <b></b>
            </i>
            <i>
              <b></b>
            </i>
            <i>
              <b></b>
            </i>
            <i>
              <b></b>
            </i>
            <i>
              <b></b>
            </i>
            <i>
              <b></b>
            </i>
            <i>
              <b></b>
            </i>
            <i>
              <b></b>
            </i>
            <i>
              <b></b>
            </i>
            <i>
              <b></b>
            </i>
            <i>
              <b></b>
            </i>
            <i>
              <b></b>
            </i>
            <i>
              <b></b>
            </i>
            <i>
              <b></b>
            </i>
            <i>
              <b></b>
            </i>
            <i>
              <b></b>
            </i>
            <i>
              <b></b>
            </i>
            <i>
              <b></b>
            </i>
            <i>
              <b></b>
            </i>
            <i>
              <b></b>
            </i>
            <i>
              <b></b>
            </i>
            <i>
              <b></b>
            </i>
            <i>
              <b></b>
            </i>
            <i>
              <b></b>
            </i>
            <i>
              <b></b>
            </i>
            <i>
              <b></b>
            </i>
            <i>
              <b></b>
            </i>
            <i>
              <b></b>
            </i>
            <i>
              <b></b>
            </i>
            <i>
              <b></b>
            </i>
            <i>
              <b></b>
            </i>
            <i>
              <b></b>
            </i>
            <i>
              <b></b>
            </i>
            <i>
              <b></b>
            </i>
            <i>
              <b></b>
            </i>
            <i>
              <b></b>
            </i>
            <i>
              <b></b>
            </i>
            <i>
              <b></b>
            </i>
            <i>
              <b></b>
            </i>
            <i>
              <b></b>
            </i>
            <i>
              <b></b>
            </i>
            <i>
              <b></b>
            </i>
            <i>
              <b></b>
            </i>
            <i>
              <b></b>
            </i>
            <i>
              <b></b>
            </i>
            <i>
              <b></b>
            </i>
            <i>
              <b></b>
            </i>
            <i>
              <b></b>
            </i>
            <i>
              <b></b>
            </i>
            <i>
              <b></b>
            </i>
            <i>
              <b></b>
            </i>
            <i>
              <b></b>
            </i>
            <i>
              <b></b>
            </i>
            <i>
              <b></b>
            </i>
            <i>
              <b></b>
            </i>
            <i>
              <b></b>
            </i>
            <i>
              <b></b>
            </i>
            <i>
              <b></b>
            </i>
            <i>
              <b></b>
            </i>
            <i>
              <b></b>
            </i>
            <i>
              <b></b>
            </i>
            <i>
              <b></b>
            </i>
            <i>
              <b></b>
            </i>
            <i>
              <b></b>
            </i>
            <i>
              <b></b>
            </i>
            <i>
              <b></b>
            </i>
            <i>
              <b></b>
            </i>
            <i>
              <b></b>
            </i>
            <i>
              <b></b>
            </i>
            <i>
              <b></b>
            </i>
            <i>
              <b></b>
            </i>
            <i>
              <b></b>
            </i>
            <i>
              <b></b>
            </i>
            <i>
              <b></b>
            </i>
            <i>
              <b></b>
            </i>
            <i>
              <b></b>
            </i>
            <i>
              <b></b>
            </i>
            <i>
              <b></b>
            </i>
            <i>
              <b></b>
            </i>
            <i>
              <b></b>
            </i>
            <i>
              <b></b>
            </i>
            <i>
              <b></b>
            </i>
            <i>
              <b></b>
            </i>
            <i>
              <b></b>
            </i>
            <i>
              <b></b>
            </i>
            <i>
              <b></b>
            </i>
            <i>
              <b></b>
            </i>
            <i>
              <b></b>
            </i>
            <i>
              <b></b>
            </i>
            <i>
              <b></b>
            </i>
            <i>
              <b></b>
            </i>
            <i>
              <b></b>
            </i>
            <i>
              <b></b>
            </i>
            <i>
              <b></b>
            </i>
            <i>
              <b></b>
            </i>
            <i>
              <b></b>
            </i>
            <i>
              <b></b>
            </i>
            <i>
              <b></b>
            </i>
          </div>
        
        )
    
}